RootPath = ../..
Sources = Canvas.cpp Element.cpp \
          Drawer.cpp Style.cpp \
	  IrrEngine.cpp InputManager.cpp
#Sources = test.cpp
Defines = AW_MODULE_GUI
Libraries = Irrlicht awcore
ProjectName = awgui
Executable = true

include $(RootPath)/Rules.mk
