RootPath    = ../..
SourceExt   = c++
Sources     =\
logging.c++ main.c++ map_loader.c++\
players/player.c++ units/unit_factory.c++
Defines     =
Libraries   = awlog awgraphics awio hdf stdc++fs
ProjectName = awrts
Executable  = true

include $(RootPath)/Rules.mk
