RootPath    = ../..
SourceExt   = c++
Sources     = video_manager.c++ model_loader.c++ \
irr/CSceneNodeAnimatorCameraRTS.c++ irr/rts_camera.c++
Defines     =
Libraries   = awlog awobj Irrlicht
ProjectName = awgraphics
Executable  = false

include $(RootPath)/Rules.mk
