RootPath    = ../..
SourceExt   = c++
Sources     = video_manager.c++ irr/CSceneNodeAnimatorCameraRTS.c++
Defines     =
Libraries   = awlog Irrlicht
ProjectName = awgraphics
Executable  = false

include $(RootPath)/Rules.mk
